spring:
  application:
    name: BlogApp
  mongodb:
    uri: mongodb+srv://BlogAppAdmin:K5IurY0SQOZVfjPd@alivinblogapp.uly6jed.mongodb.net/blogdb?retryWrites=true&w=majority&appName=AlivinBlogApp
    database: blogdb
  data:
    mongodb:
      auto-index-creation: true
#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.mongo.embedded.EmbeddedMongoAutoConfiguration

de:
  flapdoodle:
    mongodb:
      embedded:
        enabled: false


server:
  port: 8080